### ISSUE TITLE
Deprecation 'ember-views.dispatching-modify-property' triggered

### ISSUE THREAD

**Issue by marisawallace** [dollarshaveclub/ember-uni-form#2]
I'm trying out `ember-uni-form` in my app. After creating a simple form in a template:

```
  {{#uni-form action=(action 'confirmTimezone') form=uniForm}}
    {{uni-form-select payloadKey='timezone' content=timezones}}
    <button type='submit'>confirm timezone</button>
  {{/uni-form}}
```

With the following in my Component:

```
  uniForm: Ember.computed('model', function () {
    // Is this leaking memory? Do these records get cleaned up?
    return this.get('store').createRecord('uni-form', { payload: this.get('user') });
  }),
```

The form seems to work as expected, but I see the following in my console:

```
DEPRECATION: A property of <my-app@view:-outlet::ember717> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:15190:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:15100:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:15190:7)
        at invoke (http://localhost:4200/assets/vendor.js:15206:7)
        at deprecate (http://localhost:4200/assets/vendor.js:15159:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:25055:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/assets/vendor.js:51381:22)
        at http://localhost:4200/assets/vendor.js:22279:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/assets/vendor.js:30631:11)
        at Object.BasicStream.notifyExcept (http://localhost:4200/assets/vendor.js:30571:14)
        at Object.BasicStream.notify (http://localhost:4200/assets/vendor.js:30565:12)
```

Commenting out the uni-form makes the deprecation message disappear, so I can only assume it's coming from the addon. I don't have any `didInsertElement` hooks in my application. I'm using Ember 2.2.0 and Ember Data 2.2.0.

**Comment by pwfisher** [comment]
Thanks for giving it a spin =)
